@startuml
|Администратор|
start
:Инициирует добавление нового рейса;
:Вводит данные (номер поезда, маршрут);
|Система|
:Валидирует данные;
if (Данные корректны?) then (да)
  :Запрашивает список остановок;
  |Администратор|
  :Вводит остановки и время;
  |Система|
  :Сохраняет маршрут;
  :Создает сущности рейса в БД;
  :Подтверждает успех;
else (нет)
  :Показывает ошибки валидации;
endif
stop
@enduml

