' EventStorming.puml based on standard conventions

!define ES_EVENT_COLOR #Orange
!define ES_COMMAND_COLOR #DeepSkyBlue
!define ES_SYSTEM_COLOR #Pink
!define ES_AGGREGATE_COLOR #Yellow
!define ES_READ_MODEL_COLOR #LightGreen
!define ES_POLICY_COLOR #Plum
!define ES_ACTOR_COLOR #Yellow

skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam maxMessageSize 150

skinparam rectangle {
    StereotypeFontSize 12
    shadowing false
}

skinparam rectangle<<DomainEvent>> {
    BackgroundColor ES_EVENT_COLOR
    BorderColor #B25000
}

skinparam rectangle<<Command>> {
    BackgroundColor ES_COMMAND_COLOR
    BorderColor #005090
}

skinparam rectangle<<System>> {
    BackgroundColor ES_SYSTEM_COLOR
    BorderColor #B03060
}

skinparam rectangle<<Aggregate>> {
    BackgroundColor ES_AGGREGATE_COLOR
    BorderColor #A08000
}

skinparam rectangle<<ReadModel>> {
    BackgroundColor ES_READ_MODEL_COLOR
    BorderColor #307020
}

skinparam rectangle<<Policy>> {
    BackgroundColor ES_POLICY_COLOR
    BorderColor #602070
}

!define DomainEvent(e_alias, e_label) rectangle "e_label" as e_alias <<DomainEvent>>
!define Command(c_alias, c_label) rectangle "c_label" as c_alias <<Command>>
!define System(s_alias, s_label) rectangle "s_label" as s_alias <<System>>
!define Aggregate(a_alias, a_label) rectangle "a_label" as a_alias <<Aggregate>>
!define ReadModel(r_alias, r_label) rectangle "r_label" as r_alias <<ReadModel>>
!define Policy(p_alias, p_label) rectangle "p_label" as p_alias <<Policy>>
!define Actor(a_alias, a_label) actor "a_label" as a_alias

hide stereo

